### ISSUE TITLE
启动闪退

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#112]
[06-11 16:01:57] [INFO] [System]: --------加载插件--------
这是HelloWorld测试插件, 发送 helloworld 即可触发此插件。
Traceback (most recent call last):
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\main.py", line 122, in <module>
    main()
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\main.py", line 30, in main
    qqBot.initBot(cfg, provider)
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\cores\qqbot\core.py", line 296, in initBot
    ok, err = _command.plugin_reload(cached_plugins)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\model\command\command.py", line 117, in plugin_reload
    raise e
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\model\command\command.py", line 99, in plugin_reload
    obj = getattr(module, cls[0])()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\addons\plugins\HuggingChatForQQBot\HuggingChatForQQBot.py", line 14, in __init__
    self.chatbot = hugchat.ChatBot()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat.py", line 13, in __init__
    self.current_conversation = self.new_conversation()
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat.py", line 73, in new_conversation
    self.accept_ethics_modal()
  File "C:\Users\DiTing\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat.py", line 64, in accept_ethics_modal
    raise Exception(f"Failed to accept ethics modal with status code {response.status_code}. {response.content.decode()}")
Exception: Failed to accept ethics modal with status code 403. Non-JSON form requests need to have a referer

**Comment by Soulter** [comment]
HuggingChat插件没更新导致的，可以先在`addons/plugins/`目录下把它（整个文件夹）删掉，然后如果想用的话再重装。
