### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by WdmD114514** [Soulter/QQChannelChatGPT#114]
Traceback (most recent call last):
  File "C:\Users\Dell2\Desktop\QQChannelChatGPT\main.py", line 3, in <module>
    import util.general_utils as gu
  File "C:\Users\Dell2\Desktop\QQChannelChatGPT\util\general_utils.py", line 4, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
一切按照步骤进行，运行lanuncher.exe时只有这个报错了，外行人请问是哪里错了吗

**Comment by Soulter** [comment]
命令行执行命令:pip3 install Pillow
