### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ewsk233** [Soulter/QQChannelChatGPT#119]
系统centos7.6
依赖库安装完毕。
Field "model_show" has conflict with protected namespace "model_"
第三方依赖库未完全安装完毕，请退出程序重试。
退出后显示
Traceback (most recent call last):
  File "/home/QQChannelChatGPT/main.py", line 9, in main
    import cores.qqbot.core as qqBot
  File "/home/QQChannelChatGPT/cores/qqbot/core.py", line 16, in <module>
    from model.platform.qq import QQ
  File "/home/QQChannelChatGPT/model/platform/qq.py", line 1, in <module>
    from nakuru.entities.components import Plain, At, Image, Node
  File "/usr/python/lib/python3.11/site-packages/nakuru/__init__.py", line 1, in <module>
    from .application import CQHTTP
  File "/usr/python/lib/python3.11/site-packages/nakuru/application.py", line 14, in <module>
    from .event import InternalEvent, ExternalEvent
  File "/usr/python/lib/python3.11/site-packages/nakuru/event/__init__.py", line 6, in <module>
    from .enums import ExternalEventTypes
  File "/usr/python/lib/python3.11/site-packages/nakuru/event/enums.py", line 1, in <module>
    from .models import *
  File "/usr/python/lib/python3.11/site-packages/nakuru/event/models.py", line 5, in <module>
    from ..entities import Friend, Member, Anonymous, File, OfflineFile, Device, GuildMember, Reaction, Channel
  File "/usr/python/lib/python3.11/site-packages/nakuru/entities/__init__.py", line 6, in <module>
    from .others import *
  File "/usr/python/lib/python3.11/site-packages/nakuru/entities/others.py", line 104, in <module>
    class ModelShow(BaseModel):
  File "/usr/python/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/usr/python/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 112, in collect_model_fields
    raise NameError(f'Field "{ann_name}" has conflict with protected namespace "{protected_namespace}"')
NameError: Field "model_show" has conflict with protected namespace "model_"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/QQChannelChatGPT/main.py", line 122, in <module>
    main()
  File "/home/QQChannelChatGPT/main.py", line 15, in main
    input("第三方依赖库未完全安装完毕，请退出程序重试。")
KeyboardInterrupt

**Comment by Pwn1996** [comment]
我也是，卡这一步了

**Comment by Soulter** [comment]
重复issue，请看：#120
