### ISSUE TITLE
AI绘画插件

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#125]
指令调用错误: 
拉取插件失败，原因: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=master -- https://github . com/Soulter/aidraw QQChannelChatGPT/addons/plugins\aidraw
  stderr: 'Cloning into 'QQChannelChatGPT/addons/plugins\aidraw' .  .  . 
POST git-upload-pack (374 bytes)
fatal: Remote branch master not found in upstream origin
'

**Comment by Soulter** [comment]
已修复，可以重新试试

**Comment by YSDiting** [comment]
无法生成图像
[novelai] 生成图像失败: Traceback (most recent call last):
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\addons\plugins\aidraw\aidraw . py", line 146, in post
    img = r . text . split('data:')[1]
          ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\addons\plugins\aidraw\aidraw . py", line 100, in run
    filepath = self . novelai(prompt, temp_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\addons\plugins\aidraw\aidraw . py", line 138, in novelai
    filepath = self . post(post_url, header, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DiTing\Desktop\雪原bot\QQChannelChatGPT\addons\plugins\aidraw\aidraw . py", line 148, in post
    raise Exception("生成图像失败: " + r . text)
Exception: 生成图像失败: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 405 (Method Not Allowed)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www . google . com/images/errors/robot . png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www . google . com/images/logos/errorpage/error_logo-150x54 . png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www . google . com/images/logos/errorpage/error_logo-150x54-2x . png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www . google . com/images/logos/errorpage/error_logo-150x54-2x . png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www . google . com/images/logos/errorpage/error_logo-150x54-2x . png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www . google . com/><span id=logo aria-label=Google></span></a>
  <p><b>405 . </b> <ins>That’s an error . </ins>
  <p>  <ins>That’s all we know . </ins>

**Comment by Soulter** [comment]
colab部署了novelai吗

**Comment by Soulter** [comment]
https://zhuanlan.zhihu.com/p/575320094

**Comment by YSDiting** [comment]
> colab部署了novelai吗

启动模型那里一直在运行
