### ISSUE TITLE
【问题】报错：ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')

### ISSUE THREAD

**Issue by wuhonghui123** [Soulter/QQChannelChatGPT#38]
`
[INFO]  (gateway.py:110)ws_connect      [botpy] 启动中...
[INFO]  (gateway.py:136)ws_identify     [botpy] 鉴权中...
[INFO]  (gateway.py:80)on_message       [botpy] 机器人「ikunGPT-测试中」启动成功！
[INFO]  (gateway.py:217)_send_heart     [botpy] 心跳维持启动...
HTTPSConnectionPool(host='soulter.top', port=443): Max retries exceeded with url: /channelbot/update.json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
upd出现异常, 请联系QQ905617992
[QQBOT] 接收到消息：在吗
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 369, in connect
    self._tunnel()
  File "/usr/local/lib/python3.9/http/client.py", line 926, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id=6nwHRAvhqvRrd5nVbzWMxloD&client_secret=bLut9svb4T8CGfQmCIfgDmcLUYBjAWH1 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/root/qqchangpt/QQChannelChatGPT-master/cores/qqbot/core.py", line 526, in oper_msg
    check, msg = baidu_judge.judge(qq_msg)
  File "/root/qqchangpt/QQChannelChatGPT-master/addons/baidu_aip_judge.py", line 13, in judge
    res = self.client.textCensorUserDefined(text)
  File "/usr/local/lib/python3.9/site-packages/aip/imagecensor.py", line 65, in textCensorUserDefined
    return self._request(self.__textCensorUserDefinedUrl, data)
  File "/usr/local/lib/python3.9/site-packages/aip/base.py", line 92, in _request
    authObj = self._auth()
  File "/usr/local/lib/python3.9/site-packages/aip/base.py", line 166, in _auth
    obj = self.__client.get(self.__accessTokenUrl, verify=False, params={
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id=6nwHRAvhqvRrd5nVbzWMxloD&client_secret=bLut9svb4T8CGfQmCIfgDmcLUYBjAWH1 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

`

**Comment by wuhonghui123** [comment]
代理是这个，代理测试也成功了呀
# 系统代理
http_proxy: 127.0.0.1:10808
https_proxy: 127.0.0.1:10808

```
[root@VM-12-5-centos QQChannelChatGPT-master]# curl --socks5 http://127.0.0.1:10808 www.google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-MY"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="cIr6a5pOwQ2WsmWOen0grQ">(function(){window.google={kEI:'r_4PZOOYN5mF8gKp7KWoDw',kEXPI:'0,1359409,6059,206,4804,2316,383,246,5,1129120,1197756,638,380097,16114,28684,22431,1361,12311,17588,4998,13228,
```

**Comment by Soulter** [comment]
代理地址前请加上http://
