### ISSUE TITLE
这个错误怎么解决

### ISSUE THREAD

**Issue by miloce** [Soulter/QQChannelChatGPT#4]
Traceback (most recent call last):
  File "/usr/local/src/py3.9/lib/python3.9/site-packages/botpy/client.py", line 279, in _run_event
    await coro(*args, **kwargs)
  File "/root/pdbot/QQChannelChatGPT/cores/qqbot/core.py", line 46, in on_at_message_create
    await oper_msg(message=message, at=True)
  File "/root/pdbot/QQChannelChatGPT/cores/qqbot/core.py", line 268, in oper_msg
    t -= int(cache_list[index]['single_tokens'])
IndexError: list index out of range

**Comment by Soulter** [comment]
现在用的是最新的代码嘛

**Comment by miloce** [comment]
是的

**Comment by miloce** [comment]
欧克了已经解决了
