### ISSUE TITLE
ModuleNotFoundError: No module named 'aip'

### ISSUE THREAD

**Issue by vvok** [Soulter/QQChannelChatGPT#41]
运行 python3 main.py 提示：

Traceback (most recent call last):
  File "/root/qqch/QQChannelChatGPT/main.py", line 182, in <module>
    main(loop, bot_event)
  File "/root/qqch/QQChannelChatGPT/main.py", line 13, in main
    import cores.qqbot.core as qqBot
  File "/root/qqch/QQChannelChatGPT/cores/qqbot/core.py", line 18, in <module>
    from addons.baidu_aip_judge import BaiduJudge
  File "/root/qqch/QQChannelChatGPT/addons/baidu_aip_judge.py", line 1, in <module>
    from aip import AipContentCensor
ModuleNotFoundError: No module named 'aip'

换了台服务器，同样错误。

**Comment by Soulter** [comment]
没有安装baidu-aip库，执行pip install baidu-aip后重试
