### ISSUE TITLE
cmd运行源码

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#53]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import requests,json
ModuleNotFoundError: No module named 'requests'

**Comment by Soulter** [comment]
定位到项目目录下然后pip install -r requirements.txt

**Comment by YSDiting** [comment]
程序PID:10904
Traceback (most recent call last):
  File "C:\Users\DiTing\Desktop\QQChannelChatGPT-master\QQChannelChatGPT-master\main.py", line 186, in <module>
    main(loop, bot_event)
  File "C:\Users\DiTing\Desktop\QQChannelChatGPT-master\QQChannelChatGPT-master\main.py", line 13, in main
    import cores.qqbot.core as qqBot
  File "C:\Users\DiTing\Desktop\QQChannelChatGPT-master\QQChannelChatGPT-master\cores\qqbot\core.py", line 18, in <module>
    from addons.baidu_aip_judge import BaiduJudge
  File "C:\Users\DiTing\Desktop\QQChannelChatGPT-master\QQChannelChatGPT-master\addons\baidu_aip_judge.py", line 1, in <module>
    from aip import AipContentCensor
  File "C:\Users\DiTing\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aip\__init__.py", line 7, in <module>
    from .nlp import AipNlp
  File "C:\Users\DiTing\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aip\nlp.py", line 16, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

**Comment by Soulter** [comment]
pip install chardet
