### ISSUE TITLE
更新后切换模型

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#81]
模型切换不成功
[QQBOT] 接收到消息：<@!11620738824688910836> /gpt
[System] 检测到管理员身份
Exception in thread Thread-8 (oper_msg):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DiTing\Desktop\雪原Bot\QQChannelChatGPT\cores\qqbot\core.py", line 437, in oper_msg
    if len(l) >= 1 and l[1] != "":
                       ~^^^
IndexError: list index out of range

**Comment by Soulter** [comment]
已修复
