### ISSUE TITLE
newbing有点问题好像

### ISSUE THREAD

**Issue by louis26wq** [Soulter/QQChannelChatGPT#90]
4月10日的版本没问题，刚重新克隆了下项目，把旧的cookies.json放进去，并修改配置了信息后，就运行不了了。
我把gpt和bing分别建立不同的文件夹，gpt目前用的4月5日的版本，使用没问题。

python3 main.py
/root/qqchangbing/QQChannelChatGPT/main.py:80: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[System] 当前语言模型提供商: ['rev_edgegpt', 'openai_official']
Traceback (most recent call last):
  File "/root/qqchangbing/QQChannelChatGPT/main.py", line 81, in <module>
    main(loop, bot_event)
  File "/root/qqchangbing/QQChannelChatGPT/main.py", line 21, in main
    qqBot.initBot(cfg, provider)
  File "/root/qqchangbing/QQChannelChatGPT/cores/qqbot/core.py", line 193, in initBot
    rev_edgegpt = ProviderRevEdgeGPT()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/root/qqchangbing/QQChannelChatGPT/model/provider/provider_rev_edgegpt.py", line 11, in __init__
    self.bot = Chatbot(cookies=cookies)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/EdgeGPT.py", line 342, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/EdgeGPT.py", line 255, in __init__
    raise NotAllowedToAccess(self.struct["result"]["message"])
EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.

**Comment by louis26wq** [comment]
是我的问题，我重新抓取了cookies就好了
